apps/team/urls.py
from django.urls import path
from apps.team.views import Teamview


app_name = 'team'
urlpatterns = [
    path('', Teamview.as_view(), name="teams"),
]

apps/tournament/urls.py
from django.urls import path
from .views import Fixtureview, HomeView


app_name = 'fixture'
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('tournaments/<int:id>/', Fixtureview.as_view(), name="fixture"),
]

fbt2020/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.tournament.urls', 'fbt2020'), namespace="tour")),
    path('teams/', include(('apps.team.urls', 'fbt2020'), namespace="team")),
]

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/team/models.py
from django.db import models
from ..tournament.models import Tournament, Venue

class Team(models.Model):
	"""
	Tournament Team model
	"""
	name = models.CharField(max_length=50)
	description = models.TextField(null=True, blank=True)
	tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, related_name='teams', null=True)

	def __str__(self):
		return self.name


class Fixture(models.Model):
	"""
	The match between two teams
	"""
	title = models.CharField(max_length=100)
	tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, related_name="fixtures")
	a_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="a_fixture")
	b_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="b_fixture")
	venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
	date_time = models.DateTimeField()

	def __str__(self):
		return self.title

apps/tournament/models.py
from datetime import datetime, timedelta
from django.db import models

# Setting default 30 days
def now_plus_30():
	return datetime.now() + timedelta(days = 30)


class Tournament(models.Model):
	"""
	The tournament
	"""
	title = models.CharField(max_length=100)
	start_date = models.DateTimeField(auto_now_add=True, blank=True)
	end_date = models.DateTimeField(default=now_plus_30)

	def __str__(self):
		return self.title


class Venue(models.Model):
	"""
	Place of fixture
	"""
	name = models.CharField(max_length=50)
	description = models.TextField()

	def __str__(self):
		return self.name

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from ..team.models import Team


class CustomUser(AbstractUser):
	""" 
	Custom fields for team member 
	"""
	team = models.ForeignKey(Team, on_delete=models.CASCADE)
	is_coach = models.BooleanField(default=False)
	is_manager = models.BooleanField(default=False)

	def __str__(self):
		return self.username

apps/team/forms.py
from django.forms import ModelForm, DateInput
from .models import Team


class TeamForm(ModelForm):
	"""  """
	class Meta:
		model = Team
		fields = ['name', 'description',]

apps/tournament/forms.py
from django.forms import ModelForm, DateInput
from .models import Tournament
from apps.team.models import Fixture


class TournamentForm(ModelForm):
	""" Fixed start date and end date """
	class Meta:
		model = Tournament
		exclude = ['start_date', 'end_date',]


class FixtureForm(ModelForm):
	"""  """
	class Meta:
		model = Fixture
		exclude = []

apps/user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
	"""
	Create team member
	"""
	class Meta(UserCreationForm):
		model = CustomUser
		fields = ('team','is_coach','is_manager',)


class CustomUserChangeForm(UserChangeForm):
	"""
	Modify team member
	"""
	class Meta:
		model = CustomUser
		fields = ('team','is_coach','is_manager',)

apps/dashboard/views.py
from django.shortcuts import render

# Create your views here.

apps/team/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.shortcuts import get_object_or_404

from .models import Team, Fixture
from .forms import TeamForm
from apps.user.forms import CustomUserCreationForm



class Teamview(FormView):
	""" Team View - list and add teams"""
	template_name = 'teams.html'
	form_class = TeamForm
	success_url = 'teams/'

	def get_context_data(self, **kwargs):
		context = super(Teamview, self).get_context_data(**kwargs)
		teams = Team.objects.all().count()
		if teams <= 10:
			context['form'] = self.form_class
		return context

	def form_valid(self, form):
		if form.is_valid:
			form.save()
		teams = Team.objects.all().count()
		if teams == 10:
			self.create_first_round()
		return super().form_valid(form)


	def create_first_round(self):
		""" Only 4 teams for first round id 10 teams"""
		fixture = Fixture()
		first_round_teams = Team.objects.all()[:4]
		fixture.title="Round 1 A"
		fixture.tournament = first_round_teams[0].tournament
		fixture.a_team = first_round_teams[0]
		fixture.b_team = first_round_teams[1]
		fixture.date_time = tournament.start_date
		fixture.venue = Venue.objects.first()
		fixture.save()

		fixture2 = Fixture()
		fixture2.title="Round 1 B"
		fixture2.tournament = first_round_teams[0].tournament
		fixture2.a_team = first_round_teams[2]
		fixture2.b_team = first_round_teams[3]
		fixture2.date_time = tournament.start_date
		fixture2.venue = Venue.objects.first()
		fixture2.save()


class TeamDetailView(FormView):
	""" Add, view members """
	template_name = 'teams-detail.html'
	form_class = CustomUserCreationForm
	success_url = 'teams/'

	def get_context_data(self, **kwargs):
		context = super(TeamDetailView, self).get_context_data(**kwargs)
		context['form'] = self.form_class
		return context

	def form_valid(self, form):
		if form.is_valid:
			form.save()
		return super().form_valid(form)

apps/tournament/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from .models import Tournament
from .forms import TournamentForm
from django.shortcuts import get_object_or_404
from apps.team.models import Team
from .forms import FixtureForm

class HomeView(FormView):
	""" Home View - list and add tournament"""
	template_name = 'index.html'
	form_class = TournamentForm
	success_url = '/'

	def get_context_data(self, **kwargs):
		context = super(HomeView, self).get_context_data(**kwargs)
		context['form'] = self.form_class
		tours = Tournament.objects.all()
		context['tournaments'] = tours
		return context

	def form_valid(self, form):
		if form.is_valid:
			form.save()
		return super().form_valid(form)



class Fixtureview(FormView):
	""" Team View - list and add teams"""
	template_name = 'fixtures.html'
	form_class = FixtureForm
	success_url = '/'

	def get_context_data(self, **kwargs):
		context = super(Fixtureview, self).get_context_data(**kwargs)
		print(kwargs)
		context['form'] = self.form_class	
		return context

	def form_valid(self, form):
		if form.is_valid:
			form.save()
		return super().form_valid(form)

apps/user/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>FBT-2020</title>
		<!-- CSS only -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	</head>
	<body>
		<div class="container-fluid">
			<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
		  <a class="navbar-brand" href="#">FBT2020</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarCollapse">
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="/">Scoreboard<span class="sr-only">(current)</span></a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'team:teams' %}">Teams</a>
		      </li>
		      {% if user.is_staff %}
		      <li class="nav-item">
		        <a class="nav-link" href="#">Dashboard</a>
		      </li>
		      {% endif %}
		    </ul>
		  </div>
		</nav>
		<div>
			{% block content %}

			{% endblock content %}
		</div>
			<!-- JS, Popper.js, and jQuery -->
			<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
			<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
			<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
		</div>
	</body>
</html>

templates/fixtures.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<div class="container py-5">
		<h1 class="py-5 text-center text-success">Fixtures</h1>
		<div class="row">
			<div class="col col-md-6">
				<div class="shadow-sm border p-3">
					<h3>Add new Fixture</h3>
					<hr />
					<form action="." method="POST">
						{% csrf_token %}
						{{ form.as_p }}
						<input type="submit" name="submit" />
					</form>
				</div>
			</div>
			<div class="col col-md-6">
				<div class="shadow-sm border p-3">
					<h3>All Fixtures</h3>
					<hr />
					{% for fix in fixtures %}
						<a href="#">
							{{ fix.title }}
						</a>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<div class="container py-5">
		<h1 class="py-5 text-center text-success"> Welcome to FBT2020</h1>
		<div class="row">
			<div class="col col-md-6">
				<div class="shadow-sm border p-3">
					<h3>Add new Tournament</h3>
					<hr />
					<form action="." method="POST">
						{% csrf_token %}
						{{ form.as_p }}
						<input type="submit" name="submit" />
					</form>
				</div>
			</div>
			<div class="col col-md-6">
				<div class="shadow-sm border p-3">
					<h3>Tournaments</h3>
					<hr />
					{% for tour in tournaments %}
						<a href="{% url 'team:teams' tour.id %}">
							{{ tour.title }}
						</a>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

templates/teams.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<div class="container py-5">
		<h1 class="py-5 text-center text-success"> Teams</h1>
		<div class="row">
			<div class="col col-md-6">
				<div class="shadow-sm border p-3">
					<h3>Add new Team</h3>
					<hr />
					{% if form %}
					<form action="." method="POST">
						{% csrf_token %}
						{{ form.as_p }}
						<input type="submit" name="submit" />
					</form>
					{% else %}
						Registration closed
					{% endif %}
				</div>
			</div>
			<div class="col col-md-6">
				<div class="shadow-sm border p-3">
					<h3>Teams</h3>
					<hr />
					{% for team in teams %}
						<a href="#">
							{{ team.name }}
						</a>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock content %}